SELECT DISTINCT PEEVF.ELEMENT_ENTRY_VALUE_ID,
                PEEF.ELEMENT_ENTRY_ID,
                PETF.BASE_ELEMENT_NAME,
                PEEVF.SCREEN_ENTRY_VALUE,
                PEEVF.EFFECTIVE_START_DATE,
                PEEVF.EFFECTIVE_END_DATE,
                PEEVF.LAST_UPDATED_BY,
                PAAM.ASSIGNMENT_NUMBER,
                PIVF.BASE_NAME
  FROM PER_ALL_PEOPLE_F PAPF,
       PER_ALL_ASSIGNMENTS_F PAAM,
       PAY_REL_GROUPS_DN PRGD,
       PAY_ASSIGNED_PAYROLLS_DN PAPD,
       PAY_ALL_PAYROLLS_F PAY,
       PAY_ELEMENT_ENTRY_VALUES_F PEEVF,
       PAY_INPUT_VALUES_F PIVF,
       PAY_ELEMENT_ENTRIES_F PEEF,
       PAY_ELEMENT_TYPES_F PETF,
       PAY_ENTRY_USAGES PEU
 WHERE PAAM.PERSON_ID = PAPF.PERSON_ID
   AND PAAM.ASSIGNMENT_ID = PRGD.ASSIGNMENT_ID
   AND PAPD.PAYROLL_TERM_ID = PRGD.PARENT_REL_GROUP_ID
   AND PAPD.PAYROLL_ID = PAY.PAYROLL_ID
   AND PEEVF.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
   AND PIVF.ELEMENT_TYPE_ID = PETF.ELEMENT_TYPE_ID
   AND PEU.ELEMENT_ENTRY_ID = PEEF.ELEMENT_ENTRY_ID
   AND PEEVF.INPUT_VALUE_ID = PIVF.INPUT_VALUE_ID
   AND PEU.PAYROLL_RELATIONSHIP_ID = PRGD.PAYROLL_RELATIONSHIP_ID
   AND PRGD.GROUP_TYPE = 'A'
   AND PAAM.PRIMARY_FLAG = 'Y'
   AND PAAM.ASSIGNMENT_TYPE IN ( 'E' )
   AND PIVF.RESERVED_INPUT_VALUE = 'RESERVED_INPUT_VALUE'
   AND TRUNC(SYSDATE) BETWEEN PAAM.EFFECTIVE_START_DATE AND PAAM.EFFECTIVE_END_DATE
   AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
   AND TRUNC(SYSDATE) BETWEEN PRGD.START_DATE AND PRGD.END_DATE
   AND TRUNC(SYSDATE) BETWEEN PAY.EFFECTIVE_START_DATE (+) AND PAY.EFFECTIVE_END_DATE (+)
   AND TRUNC(SYSDATE) BETWEEN PIVF.EFFECTIVE_START_DATE AND PIVF.EFFECTIVE_END_DATE
   AND TRUNC(SYSDATE) BETWEEN PETF.EFFECTIVE_START_DATE AND PETF.EFFECTIVE_END_DATE

   /* Input Parameters */
   AND ( PAPF.PERSON_NUMBER = :PERSON_NUMBER
    OR PAPF.PERSON_ID = :PERSON_ID )
   AND PETF.BASE_ELEMENT_NAME IN ( :ELEMENT_NAME )
   /* Extra Conditions */
   --AND PAAM.ASSIGNMENT_STATUS_TYPE = 'ACTIVE'
   --AND PIVF.BASE_NAME = 'Amount'
   --AND PETF.BASE_ELEMENT_NAME IN ( 'Y_401K' )
   --AND PAAM.ASSIGNMENT_NUMBER LIKE 'E10037489%'
 ORDER BY PAAM.ASSIGNMENT_NUMBER,
          PEEVF.EFFECTIVE_START_DATE